jobs:
  - job: MacOS
    pool:
      vmImage: macOS-10.14
    steps:
      - template: darwin/continuous-build-darwin.yml

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - template: win32/continuous-build-win32.yml

  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: linux/continuous-build-linux.yml
  
  - job: ScanForVulnerabilities
    pool:
      vmImage: vs2017-win2016
    steps:
      - task: Bandit@1
        inputs:
          targetsType: 'banditPattern'
          targetsBandit: '$(Build.SourcesDirectory)'
          targetsBanditRecursive: true
          ruleset: 'guardian'
          verbose: true
          aggregate: 'file'
      - script: |
          for /f %%a IN ('dir /b /s "D:\a\1\.gdn\r\*"') DO cat %%a
          
  - job: LegalStatusPolicyCheck
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: policy/continuous-legal-status-policy-check.yml

  - job: PublishStandaloneBinariesForWin32
    dependsOn:
      - MacOS
      - Windows
      - Linux
    pool:
      vmImage: windows-2019
    steps:
      - template: standalone-binaries/continuous-build-standalone-binaries-win32.yml
    condition: and(succeeded('Windows'), succeeded('Linux'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

  - job: PublishDropFile
    dependsOn:
      - MacOS
      - Windows
      - Linux
    condition: and(succeeded('Windows'), succeeded('Linux'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    pool:
      vmImage: "ubuntu-16.04"

    steps:
      - task: UsePythonVersion@0
        displayName: "Use Python 3.7"
        inputs:
          versionSpec: 3.7
          addToPath: true
          architecture: "x64"

      - powershell: |
          echo $(BUILD.SOURCEBRANCH)
          if ("$(BUILD.SOURCEBRANCH)" -match "^refs/tags/v?[0-9]+\.[0-9]+\.[0-9]+$") { ((Get-Content -path "$(BUILD.REPOSITORY.LOCALPATH)\iotedgehubdev\__init__.py" -Raw) -replace "__AIkey__ = '.*'","__AIkey__ = '$(AI_KEY)'") | Set-Content -Path "$(BUILD.REPOSITORY.LOCALPATH)\iotedgehubdev\__init__.py" }
        displayName: "Replace AI Key for PROD"

      - script: |
          pip install setuptools
          pip install wheel
          pushd $(BUILD.REPOSITORY.LOCALPATH)
          python setup.py bdist_wheel
          popd
        displayName: "Build drop file"

      - task: CopyFiles@2
        inputs:
          SourceFolder: $(BUILD.REPOSITORY.LOCALPATH)/dist
          TargetFolder: $(Build.ArtifactStagingDirectory)
        displayName: "Copy Files to: build artifact staging directory"

      - task: EsrpCodeSigning@1
        inputs:
          ConnectedServiceName: 'IoT Edge NuGet Sign - DDE'
          FolderPath: '$(Build.ArtifactStagingDirectory)'
          Pattern: 'iotedgehubdev.exe'
          signConfigType: 'inlineSignParams'
          # 9990 : Microsoft Corporation (Compressed Binaries SHA2 Root - Standard Root)
          # https://microsoft.sharepoint.com/teams/codesigninfo/Wiki/Json%20Builder%20-%20ESRP%20Client.aspx?kc1=CP-230012&os1=SigntoolSign&cp1=OpusName%3DMicrosoft%3bOpusInfo%3Dhttp%3a//www.microsoft.com%3bFileDigest%3D/fd%20%5c%22SHA256%5c%22%3bPageHash%3D/NPH%3bTimeStamp%3D/tr%20%5c%22http%3a//rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer%5c%22%20/td%20sha256&kc2=CP-230012&os2=SigntoolVerify
          inlineOperation: |
            [
                    {
                        "KeyCode" : "CP-230012",
                        "OperationCode" : "SigntoolSign",
                        "Parameters" : {
                            "OpusName" : "Microsoft",
                            "OpusInfo" : "http://www.microsoft.com",
                            "FileDigest" : "/fd \"SHA256\"",
                            "PageHash" : "/NPH",
                            "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                        },
                        "ToolName" : "sign",
                        "ToolVersion" : "1.0"
                    },
                    {
                        "KeyCode" : "CP-230012",
                        "OperationCode" : "SigntoolVerify",
                        "Parameters" : {},
                        "ToolName" : "sign",
                        "ToolVersion" : "1.0"
                    }
                ]
          SessionTimeout: '60'
          MaxConcurrency: '50'
          MaxRetryAttempts: '5'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: build-artifact-drop
